export const ENEMY_CONFIG = {
  octopus: {
    key: 'enemy-octopus',
    name: 'Octopus',
    hp: 50,
    speed: 45,
    damage: 1,
    reward: 15,
  },
  caterpillar: {
    key: 'enemy-caterpillar',
    name: 'Caterpillar',
    hp: 35,
    speed: 90,
    damage: 1,
    reward: 20,
  },
  robot: {
    key: 'enemy-robot',
    name: 'Robot',
    hp: 120,
    speed: 40,
    damage: 2,
    shield: 30,
    reward: 30,
  },
  jellyfish: {
    key: 'enemy-jellyfish',
    name: 'Jellyfish',
    hp: 65,
    speed: 60,
    damage: 1,
    immuneSlow: true,
    reward: 25,
  },
  boss: {
    key: 'enemy-boss',
    name: 'Big Eye Boss',
    hp: 500,
    speed: 30,
    damage: 5,
    reward: 100,
    summonInterval: 8000,
    summonCount: 3,
  },
};
