export const LEVELS = [
  // Level 1: First Contact - Simple S-bend
  {
    id: 1,
    name: 'First Contact',
    description: 'The invasion begins...',
    path: [
      { col: 0, row: 3 }, { col: 6, row: 3 }, { col: 6, row: 9 },
      { col: 1, row: 9 }, { col: 1, row: 13 }, { col: 10, row: 13 },
      { col: 10, row: 7 }, { col: 18, row: 7 }, { col: 18, row: 12 },
      { col: 23, row: 12 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 5, interval: 1500 }] },
      { enemies: [{ type: 'octopus', count: 8, interval: 1200 }] },
      { enemies: [{ type: 'octopus', count: 10, interval: 1000 }] },
      { enemies: [{ type: 'caterpillar', count: 6, interval: 900 }] },
      { enemies: [{ type: 'caterpillar', count: 8, interval: 800 }, { type: 'octopus', count: 4, interval: 1200 }] },
    ],
    hpMultiplier: 1.0,
    speedMultiplier: 1.0,
    startCoins: 300,
    specialRule: null,
  },
  // Level 2: Winding Stars - Double Z-zigzag
  {
    id: 2,
    name: 'Winding Stars',
    description: 'A twisting path through the stars.',
    path: [
      { col: 0, row: 2 }, { col: 8, row: 2 }, { col: 8, row: 6 },
      { col: 2, row: 6 }, { col: 2, row: 10 }, { col: 12, row: 10 },
      { col: 12, row: 3 }, { col: 20, row: 3 }, { col: 20, row: 10 },
      { col: 23, row: 10 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 8, interval: 1200 }] },
      { enemies: [{ type: 'caterpillar', count: 8, interval: 900 }] },
      { enemies: [{ type: 'octopus', count: 10, interval: 1000 }, { type: 'caterpillar', count: 5, interval: 800 }] },
      { enemies: [{ type: 'robot', count: 3, interval: 2000 }] },
      { enemies: [{ type: 'caterpillar', count: 10, interval: 700 }, { type: 'robot', count: 3, interval: 1800 }] },
    ],
    hpMultiplier: 1.3,
    speedMultiplier: 1.0,
    startCoins: 300,
    specialRule: null,
  },
  // Level 3: Nebula Maze - Triple fold
  {
    id: 3,
    name: 'Nebula Maze',
    description: 'Navigate the cosmic labyrinth.',
    path: [
      { col: 0, row: 1 }, { col: 5, row: 1 }, { col: 5, row: 5 },
      { col: 1, row: 5 }, { col: 1, row: 9 }, { col: 7, row: 9 },
      { col: 7, row: 13 }, { col: 14, row: 13 }, { col: 14, row: 5 },
      { col: 20, row: 5 }, { col: 20, row: 12 }, { col: 23, row: 12 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 10, interval: 1000 }] },
      { enemies: [{ type: 'caterpillar', count: 10, interval: 800 }] },
      { enemies: [{ type: 'robot', count: 5, interval: 1800 }] },
      { enemies: [{ type: 'caterpillar', count: 12, interval: 600 }, { type: 'octopus', count: 6, interval: 1000 }] },
      { enemies: [{ type: 'robot', count: 6, interval: 1500 }, { type: 'caterpillar', count: 8, interval: 700 }] },
      { enemies: [{ type: 'jellyfish', count: 5, interval: 1200 }] },
    ],
    hpMultiplier: 1.5,
    speedMultiplier: 1.1,
    startCoins: 300,
    specialRule: null,
  },
  // Level 4: Speed Swarm - Short path, fast enemies
  {
    id: 4,
    name: 'Speed Swarm',
    description: 'They come fast! Short path, no time to waste.',
    path: [
      { col: 0, row: 7 }, { col: 6, row: 7 }, { col: 6, row: 3 },
      { col: 14, row: 3 }, { col: 14, row: 11 }, { col: 23, row: 11 },
    ],
    waves: [
      { enemies: [{ type: 'caterpillar', count: 12, interval: 600 }] },
      { enemies: [{ type: 'caterpillar', count: 15, interval: 500 }] },
      { enemies: [{ type: 'caterpillar', count: 12, interval: 500 }, { type: 'octopus', count: 8, interval: 800 }] },
      { enemies: [{ type: 'jellyfish', count: 8, interval: 700 }] },
      { enemies: [{ type: 'caterpillar', count: 20, interval: 400 }, { type: 'jellyfish', count: 6, interval: 600 }] },
    ],
    hpMultiplier: 1.5,
    speedMultiplier: 1.4,
    startCoins: 350,
    specialRule: 'speed-swarm',
  },
  // Level 5: Shield Wall - Robots dominate
  {
    id: 5,
    name: 'Shield Wall',
    description: 'Heavy armored robots march forward.',
    path: [
      { col: 0, row: 4 }, { col: 4, row: 4 }, { col: 4, row: 10 },
      { col: 10, row: 10 }, { col: 10, row: 2 }, { col: 16, row: 2 },
      { col: 16, row: 12 }, { col: 23, row: 12 },
    ],
    waves: [
      { enemies: [{ type: 'robot', count: 5, interval: 2000 }] },
      { enemies: [{ type: 'robot', count: 8, interval: 1800 }] },
      { enemies: [{ type: 'robot', count: 6, interval: 1500 }, { type: 'octopus', count: 10, interval: 1000 }] },
      { enemies: [{ type: 'robot', count: 10, interval: 1500 }] },
      { enemies: [{ type: 'robot', count: 8, interval: 1200 }, { type: 'caterpillar', count: 12, interval: 600 }] },
      { enemies: [{ type: 'robot', count: 12, interval: 1200 }, { type: 'jellyfish', count: 5, interval: 1000 }] },
    ],
    hpMultiplier: 2.0,
    speedMultiplier: 1.1,
    startCoins: 300,
    specialRule: null,
  },
  // Level 6: Ghost Tide - Jellyfish immune to slow
  {
    id: 6,
    name: 'Ghost Tide',
    description: 'Frost towers are useless here.',
    path: [
      { col: 0, row: 8 }, { col: 3, row: 8 }, { col: 3, row: 2 },
      { col: 9, row: 2 }, { col: 9, row: 12 }, { col: 15, row: 12 },
      { col: 15, row: 4 }, { col: 21, row: 4 }, { col: 21, row: 10 },
      { col: 23, row: 10 },
    ],
    waves: [
      { enemies: [{ type: 'jellyfish', count: 10, interval: 1000 }] },
      { enemies: [{ type: 'jellyfish', count: 12, interval: 800 }] },
      { enemies: [{ type: 'jellyfish', count: 10, interval: 800 }, { type: 'octopus', count: 8, interval: 1000 }] },
      { enemies: [{ type: 'jellyfish', count: 15, interval: 700 }] },
      { enemies: [{ type: 'jellyfish', count: 12, interval: 600 }, { type: 'robot', count: 5, interval: 1500 }] },
      { enemies: [{ type: 'jellyfish', count: 15, interval: 500 }, { type: 'caterpillar', count: 10, interval: 600 }] },
    ],
    hpMultiplier: 2.5,
    speedMultiplier: 1.2,
    startCoins: 300,
    specialRule: null,
  },
  // Level 7: Twin Paths - Two entry points
  {
    id: 7,
    name: 'Twin Paths',
    description: 'They attack from two directions!',
    path: [
      { col: 0, row: 3 }, { col: 6, row: 3 }, { col: 6, row: 8 },
      { col: 12, row: 8 }, { col: 12, row: 12 }, { col: 23, row: 12 },
    ],
    path2: [
      { col: 0, row: 13 }, { col: 6, row: 13 }, { col: 6, row: 8 },
      { col: 12, row: 8 }, { col: 12, row: 12 }, { col: 23, row: 12 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 8, interval: 1000 }] },
      { enemies: [{ type: 'caterpillar', count: 10, interval: 800 }] },
      { enemies: [{ type: 'robot', count: 6, interval: 1500 }, { type: 'octopus', count: 8, interval: 900 }] },
      { enemies: [{ type: 'jellyfish', count: 10, interval: 800 }, { type: 'caterpillar', count: 10, interval: 700 }] },
      { enemies: [{ type: 'robot', count: 8, interval: 1200 }, { type: 'jellyfish', count: 8, interval: 900 }] },
      { enemies: [{ type: 'robot', count: 6, interval: 1000 }, { type: 'jellyfish', count: 8, interval: 800 }, { type: 'caterpillar', count: 10, interval: 600 }] },
    ],
    hpMultiplier: 2.5,
    speedMultiplier: 1.2,
    startCoins: 350,
    specialRule: 'twin-paths',
  },
  // Level 8: Resource Famine - Less starting coins
  {
    id: 8,
    name: 'Resource Famine',
    description: 'Resources are scarce. Spend wisely.',
    path: [
      { col: 0, row: 2 }, { col: 4, row: 2 }, { col: 4, row: 7 },
      { col: 1, row: 7 }, { col: 1, row: 12 }, { col: 8, row: 12 },
      { col: 8, row: 4 }, { col: 14, row: 4 }, { col: 14, row: 13 },
      { col: 20, row: 13 }, { col: 20, row: 6 }, { col: 23, row: 6 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 12, interval: 900 }] },
      { enemies: [{ type: 'caterpillar', count: 12, interval: 700 }] },
      { enemies: [{ type: 'robot', count: 8, interval: 1500 }] },
      { enemies: [{ type: 'jellyfish', count: 10, interval: 800 }, { type: 'octopus', count: 8, interval: 900 }] },
      { enemies: [{ type: 'robot', count: 8, interval: 1200 }, { type: 'caterpillar', count: 12, interval: 600 }] },
      { enemies: [{ type: 'jellyfish', count: 10, interval: 700 }, { type: 'robot', count: 6, interval: 1200 }] },
      { enemies: [{ type: 'robot', count: 10, interval: 1000 }, { type: 'jellyfish', count: 8, interval: 800 }, { type: 'caterpillar', count: 10, interval: 600 }] },
    ],
    hpMultiplier: 3.0,
    speedMultiplier: 1.3,
    startCoins: 200,
    specialRule: 'famine',
  },
  // Level 9: All Out - Everything mixed
  {
    id: 9,
    name: 'All Out',
    description: 'Every enemy type at full force.',
    path: [
      { col: 0, row: 1 }, { col: 7, row: 1 }, { col: 7, row: 6 },
      { col: 2, row: 6 }, { col: 2, row: 11 }, { col: 10, row: 11 },
      { col: 10, row: 3 }, { col: 17, row: 3 }, { col: 17, row: 13 },
      { col: 22, row: 13 }, { col: 22, row: 7 }, { col: 23, row: 7 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 15, interval: 800 }] },
      { enemies: [{ type: 'caterpillar', count: 15, interval: 600 }] },
      { enemies: [{ type: 'robot', count: 10, interval: 1200 }] },
      { enemies: [{ type: 'jellyfish', count: 12, interval: 700 }] },
      { enemies: [{ type: 'octopus', count: 10, interval: 700 }, { type: 'caterpillar', count: 10, interval: 600 }, { type: 'robot', count: 5, interval: 1200 }] },
      { enemies: [{ type: 'jellyfish', count: 10, interval: 600 }, { type: 'robot', count: 8, interval: 1000 }] },
      { enemies: [{ type: 'octopus', count: 12, interval: 600 }, { type: 'caterpillar', count: 12, interval: 500 }, { type: 'jellyfish', count: 8, interval: 700 }, { type: 'robot', count: 6, interval: 1000 }] },
      { enemies: [{ type: 'boss', count: 1, interval: 1000 }, { type: 'octopus', count: 10, interval: 800 }] },
    ],
    hpMultiplier: 4.0,
    speedMultiplier: 1.3,
    startCoins: 300,
    specialRule: null,
  },
  // Level 10: Final Stand - Double boss
  {
    id: 10,
    name: 'Final Stand',
    description: 'Two bosses. No mercy.',
    path: [
      { col: 0, row: 4 }, { col: 5, row: 4 }, { col: 5, row: 1 },
      { col: 11, row: 1 }, { col: 11, row: 8 }, { col: 3, row: 8 },
      { col: 3, row: 13 }, { col: 13, row: 13 }, { col: 13, row: 5 },
      { col: 19, row: 5 }, { col: 19, row: 13 }, { col: 23, row: 13 },
    ],
    waves: [
      { enemies: [{ type: 'octopus', count: 15, interval: 700 }, { type: 'caterpillar', count: 10, interval: 600 }] },
      { enemies: [{ type: 'robot', count: 10, interval: 1200 }, { type: 'jellyfish', count: 10, interval: 800 }] },
      { enemies: [{ type: 'caterpillar', count: 20, interval: 400 }] },
      { enemies: [{ type: 'robot', count: 12, interval: 1000 }, { type: 'octopus', count: 15, interval: 600 }] },
      { enemies: [{ type: 'jellyfish', count: 15, interval: 600 }, { type: 'robot', count: 8, interval: 1000 }] },
      { enemies: [{ type: 'octopus', count: 15, interval: 500 }, { type: 'caterpillar', count: 15, interval: 400 }, { type: 'robot', count: 8, interval: 1000 }, { type: 'jellyfish', count: 8, interval: 700 }] },
      { enemies: [{ type: 'boss', count: 2, interval: 5000 }, { type: 'robot', count: 6, interval: 1200 }, { type: 'jellyfish', count: 8, interval: 800 }] },
    ],
    hpMultiplier: 5.0,
    speedMultiplier: 1.4,
    startCoins: 400,
    specialRule: 'dual-boss',
  },
];
