export const TOWER_CONFIG = {
  star: {
    key: 'tower-star',
    upKey: 'tower-star-up',
    name: 'Star Tower',
    cost: 100,
    damage: 10,
    range: 120,
    fireRate: 800,
    projectile: 'proj-star',
    description: 'Basic shooter',
    detailText: 'Reliable single-target shooter. Cheap and effective for early waves.',
  },
  frost: {
    key: 'tower-frost',
    upKey: 'tower-frost-up',
    name: 'Frost Tower',
    cost: 150,
    damage: 6,
    range: 110,
    fireRate: 1000,
    projectile: 'proj-ice',
    slowFactor: 0.5,
    slowDuration: 2000,
    description: 'Slows enemies',
    detailText: 'Slows enemies by 50% for 2s. Immune to Ghost Jellyfish.',
  },
  meteor: {
    key: 'tower-meteor',
    upKey: 'tower-meteor-up',
    name: 'Meteor Tower',
    cost: 200,
    damage: 20,
    range: 160,
    fireRate: 1500,
    projectile: 'proj-meteor',
    splashRadius: 80,
    description: 'Area damage',
    detailText: 'Projectile explodes on impact dealing splash damage in a wide radius.',
  },
  heal: {
    key: 'tower-heal',
    upKey: 'tower-heal-up',
    name: 'Heal Tower',
    cost: 250,
    healAmount: 1,
    range: 0,
    fireRate: 5000,
    description: 'Heals planet',
    detailText: 'Does not attack. Periodically restores 1 planet HP. Scales with upgrade.',
  },
  blackhole: {
    key: 'tower-blackhole',
    upKey: 'tower-blackhole-up',
    name: 'Black Hole',
    cost: 300,
    damage: 5,
    range: 150,
    fireRate: 1500,
    pullStrength: 30,
    description: 'Pulls enemies',
    detailText: 'Pauses nearby enemies and deals damage. Great crowd control.',
  },
};
